name: Deploy Umurava Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 10039
          script: |
            cd /home/administrator/umuravalens-backend
            git pull origin main
            
            # Use GitHub Secrets to build the .env file
            echo "${{ secrets.ENV_FILE }}" > .env
            
            # Build and restart containers
            docker compose up --build -d
            
            # Cleanup old images to prevent Ubuntu 24.04 disk from filling up
            docker image prune -f